import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../styles/style.scss'

import BottomSheetController from '@/components/ui/BottomSheetController'
import PopupController from '@/components/ui/PopupController'
import Footer from '@/components/ui/Footer'
import Header from '@/components/ui/Header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="wrap">
          <Header />
          {children}
          <Footer />
        </div>
        <BottomSheetController />
        <PopupController />
      </body>
    </html>
  )
}
